package pe.edu.upc.innovaschool.model;
// Generated 06-sep-2016 10:42:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ExpedienteAdmision generated by hbm2java
 */
public class ExpedienteAdmision  implements java.io.Serializable {


     private int idExpedienteAdmision;
     private Alumno alumno;
     private Date fechaRegistro;
     private String estado;
     private Set solicitudAdmisions = new HashSet(0);

    public ExpedienteAdmision() {
    }

	
    public ExpedienteAdmision(int idExpedienteAdmision) {
        this.idExpedienteAdmision = idExpedienteAdmision;
    }
    public ExpedienteAdmision(int idExpedienteAdmision, Alumno alumno, Date fechaRegistro, String estado, Set solicitudAdmisions) {
       this.idExpedienteAdmision = idExpedienteAdmision;
       this.alumno = alumno;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
       this.solicitudAdmisions = solicitudAdmisions;
    }
   
    public int getIdExpedienteAdmision() {
        return this.idExpedienteAdmision;
    }
    
    public void setIdExpedienteAdmision(int idExpedienteAdmision) {
        this.idExpedienteAdmision = idExpedienteAdmision;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getSolicitudAdmisions() {
        return this.solicitudAdmisions;
    }
    
    public void setSolicitudAdmisions(Set solicitudAdmisions) {
        this.solicitudAdmisions = solicitudAdmisions;
    }




}


