package pe.edu.upc.innovaschool.model;
// Generated 06-sep-2016 10:42:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idPersona;
     private DocumentoIdentidad documentoIdentidad;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String direccion;
     private String telefono;
     private String correoElectronico;
     private String documentoIdentidad_1;
     private String nacionalidad;
     private String genero;
     private String telefonoEmergencia;
     private String contactoEmergencia;
     private Date fechaNacimiento;
     private String gradoEstudios;
     private String celular;
     private String usuarioCreacion;
     private Date fechaCreacion;
     private String usuarioModificacion;
     private Date fechaModificacion;
     private Set apoderados = new HashSet(0);
     private Set alumnos = new HashSet(0);

    public Persona() {
    }

	
    public Persona(int idPersona) {
        this.idPersona = idPersona;
    }
    public Persona(int idPersona, DocumentoIdentidad documentoIdentidad, String nombre, String apellidoPaterno, String apellidoMaterno, String direccion, String telefono, String correoElectronico, String documentoIdentidad_1, String nacionalidad, String genero, String telefonoEmergencia, String contactoEmergencia, Date fechaNacimiento, String gradoEstudios, String celular, String usuarioCreacion, Date fechaCreacion, String usuarioModificacion, Date fechaModificacion, Set apoderados, Set alumnos) {
       this.idPersona = idPersona;
       this.documentoIdentidad = documentoIdentidad;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.direccion = direccion;
       this.telefono = telefono;
       this.correoElectronico = correoElectronico;
       this.documentoIdentidad_1 = documentoIdentidad_1;
       this.nacionalidad = nacionalidad;
       this.genero = genero;
       this.telefonoEmergencia = telefonoEmergencia;
       this.contactoEmergencia = contactoEmergencia;
       this.fechaNacimiento = fechaNacimiento;
       this.gradoEstudios = gradoEstudios;
       this.celular = celular;
       this.usuarioCreacion = usuarioCreacion;
       this.fechaCreacion = fechaCreacion;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
       this.apoderados = apoderados;
       this.alumnos = alumnos;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public DocumentoIdentidad getDocumentoIdentidad() {
        return this.documentoIdentidad;
    }
    
    public void setDocumentoIdentidad(DocumentoIdentidad documentoIdentidad) {
        this.documentoIdentidad = documentoIdentidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getDocumentoIdentidad_1() {
        return this.documentoIdentidad_1;
    }
    
    public void setDocumentoIdentidad_1(String documentoIdentidad_1) {
        this.documentoIdentidad_1 = documentoIdentidad_1;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getTelefonoEmergencia() {
        return this.telefonoEmergencia;
    }
    
    public void setTelefonoEmergencia(String telefonoEmergencia) {
        this.telefonoEmergencia = telefonoEmergencia;
    }
    public String getContactoEmergencia() {
        return this.contactoEmergencia;
    }
    
    public void setContactoEmergencia(String contactoEmergencia) {
        this.contactoEmergencia = contactoEmergencia;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getGradoEstudios() {
        return this.gradoEstudios;
    }
    
    public void setGradoEstudios(String gradoEstudios) {
        this.gradoEstudios = gradoEstudios;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getApoderados() {
        return this.apoderados;
    }
    
    public void setApoderados(Set apoderados) {
        this.apoderados = apoderados;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }




}


