package pe.edu.upc.innovaschool.model;
// Generated 06-sep-2016 10:42:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proceso generated by hbm2java
 */
public class Proceso  implements java.io.Serializable {


     private int idProceso;
     private Cronograma cronograma;
     private String tipo;
     private Date fechaInicio;
     private Date fechaFin;
     private Set citas = new HashSet(0);

    public Proceso() {
    }

	
    public Proceso(int idProceso) {
        this.idProceso = idProceso;
    }
    public Proceso(int idProceso, Cronograma cronograma, String tipo, Date fechaInicio, Date fechaFin, Set citas) {
       this.idProceso = idProceso;
       this.cronograma = cronograma;
       this.tipo = tipo;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.citas = citas;
    }
   
    public int getIdProceso() {
        return this.idProceso;
    }
    
    public void setIdProceso(int idProceso) {
        this.idProceso = idProceso;
    }
    public Cronograma getCronograma() {
        return this.cronograma;
    }
    
    public void setCronograma(Cronograma cronograma) {
        this.cronograma = cronograma;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }




}


