package pe.edu.upc.innovaschool.model;
// Generated 06-sep-2016 10:42:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SolicitudAdmision generated by hbm2java
 */
public class SolicitudAdmision  implements java.io.Serializable {


     private int nroSolicitud;
     private Alumno alumno;
     private ExpedienteAdmision expedienteAdmision;
     private Grado grado;
     private Date fechaSolicitud;

    public SolicitudAdmision() {
    }

	
    public SolicitudAdmision(int nroSolicitud) {
        this.nroSolicitud = nroSolicitud;
    }
    public SolicitudAdmision(int nroSolicitud, Alumno alumno, ExpedienteAdmision expedienteAdmision, Grado grado, Date fechaSolicitud) {
       this.nroSolicitud = nroSolicitud;
       this.alumno = alumno;
       this.expedienteAdmision = expedienteAdmision;
       this.grado = grado;
       this.fechaSolicitud = fechaSolicitud;
    }
   
    public int getNroSolicitud() {
        return this.nroSolicitud;
    }
    
    public void setNroSolicitud(int nroSolicitud) {
        this.nroSolicitud = nroSolicitud;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public ExpedienteAdmision getExpedienteAdmision() {
        return this.expedienteAdmision;
    }
    
    public void setExpedienteAdmision(ExpedienteAdmision expedienteAdmision) {
        this.expedienteAdmision = expedienteAdmision;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }




}


