package pe.edu.upc.innovaschool.model;
// Generated 06-sep-2016 10:42:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int idAlumno;
     private Apoderado apoderado;
     private Sede sede;
     private Persona persona;
     private String estado;
     private Set solicitudAdmisions = new HashSet(0);
     private Set expedienteAdmisions = new HashSet(0);
     private Set citas = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }
    public Alumno(int idAlumno, Apoderado apoderado, Sede sede, Persona persona, String estado, Set solicitudAdmisions, Set expedienteAdmisions, Set citas) {
       this.idAlumno = idAlumno;
       this.apoderado = apoderado;
       this.sede = sede;
       this.persona = persona;
       this.estado = estado;
       this.solicitudAdmisions = solicitudAdmisions;
       this.expedienteAdmisions = expedienteAdmisions;
       this.citas = citas;
    }
   
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }
    public Apoderado getApoderado() {
        return this.apoderado;
    }
    
    public void setApoderado(Apoderado apoderado) {
        this.apoderado = apoderado;
    }
    public Sede getSede() {
        return this.sede;
    }
    
    public void setSede(Sede sede) {
        this.sede = sede;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getSolicitudAdmisions() {
        return this.solicitudAdmisions;
    }
    
    public void setSolicitudAdmisions(Set solicitudAdmisions) {
        this.solicitudAdmisions = solicitudAdmisions;
    }
    public Set getExpedienteAdmisions() {
        return this.expedienteAdmisions;
    }
    
    public void setExpedienteAdmisions(Set expedienteAdmisions) {
        this.expedienteAdmisions = expedienteAdmisions;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }




}


