package pe.edu.upc.innovaschool.model;
// Generated 06-sep-2016 10:42:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cita generated by hbm2java
 */
public class Cita  implements java.io.Serializable {


     private int idCita;
     private Alumno alumno;
     private Proceso proceso;
     private Sede sede;
     private String estado;
     private Date fechaCita;
     private String horaCita;
     private String tipo;
     private int idEmpleado;

    public Cita() {
    }

	
    public Cita(int idCita, Proceso proceso, int idEmpleado) {
        this.idCita = idCita;
        this.proceso = proceso;
        this.idEmpleado = idEmpleado;
    }
    public Cita(int idCita, Alumno alumno, Proceso proceso, Sede sede, String estado, Date fechaCita, String horaCita, String tipo, int idEmpleado) {
       this.idCita = idCita;
       this.alumno = alumno;
       this.proceso = proceso;
       this.sede = sede;
       this.estado = estado;
       this.fechaCita = fechaCita;
       this.horaCita = horaCita;
       this.tipo = tipo;
       this.idEmpleado = idEmpleado;
    }
   
    public int getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(int idCita) {
        this.idCita = idCita;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Proceso getProceso() {
        return this.proceso;
    }
    
    public void setProceso(Proceso proceso) {
        this.proceso = proceso;
    }
    public Sede getSede() {
        return this.sede;
    }
    
    public void setSede(Sede sede) {
        this.sede = sede;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaCita() {
        return this.fechaCita;
    }
    
    public void setFechaCita(Date fechaCita) {
        this.fechaCita = fechaCita;
    }
    public String getHoraCita() {
        return this.horaCita;
    }
    
    public void setHoraCita(String horaCita) {
        this.horaCita = horaCita;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }




}


