package pe.edu.upc.innovaschool.model;
// Generated 06-sep-2016 10:42:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cronograma generated by hbm2java
 */
public class Cronograma  implements java.io.Serializable {


     private int idCronograma;
     private String description;
     private Date fechaInicio;
     private Date fechaFin;
     private Set procesos = new HashSet(0);

    public Cronograma() {
    }

	
    public Cronograma(int idCronograma) {
        this.idCronograma = idCronograma;
    }
    public Cronograma(int idCronograma, String description, Date fechaInicio, Date fechaFin, Set procesos) {
       this.idCronograma = idCronograma;
       this.description = description;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.procesos = procesos;
    }
   
    public int getIdCronograma() {
        return this.idCronograma;
    }
    
    public void setIdCronograma(int idCronograma) {
        this.idCronograma = idCronograma;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Set getProcesos() {
        return this.procesos;
    }
    
    public void setProcesos(Set procesos) {
        this.procesos = procesos;
    }




}


