package pe.edu.upc.innovaschool.model;
// Generated 06-sep-2016 10:42:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grado generated by hbm2java
 */
public class Grado  implements java.io.Serializable {


     private int idGrado;
     private Nivel nivel;
     private String nombre;
     private String descripcion;
     private Set solicitudAdmisions = new HashSet(0);

    public Grado() {
    }

	
    public Grado(int idGrado, Nivel nivel, String nombre) {
        this.idGrado = idGrado;
        this.nivel = nivel;
        this.nombre = nombre;
    }
    public Grado(int idGrado, Nivel nivel, String nombre, String descripcion, Set solicitudAdmisions) {
       this.idGrado = idGrado;
       this.nivel = nivel;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.solicitudAdmisions = solicitudAdmisions;
    }
   
    public int getIdGrado() {
        return this.idGrado;
    }
    
    public void setIdGrado(int idGrado) {
        this.idGrado = idGrado;
    }
    public Nivel getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Nivel nivel) {
        this.nivel = nivel;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSolicitudAdmisions() {
        return this.solicitudAdmisions;
    }
    
    public void setSolicitudAdmisions(Set solicitudAdmisions) {
        this.solicitudAdmisions = solicitudAdmisions;
    }




}


