package pe.edu.upc.innovaschool.model;
// Generated 06-sep-2016 10:42:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sede generated by hbm2java
 */
public class Sede  implements java.io.Serializable {


     private int idSede;
     private String nombre;
     private String descripcion;
     private String direccion;
     private Set citas = new HashSet(0);
     private Set alumnos = new HashSet(0);

    public Sede() {
    }

	
    public Sede(int idSede) {
        this.idSede = idSede;
    }
    public Sede(int idSede, String nombre, String descripcion, String direccion, Set citas, Set alumnos) {
       this.idSede = idSede;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.direccion = direccion;
       this.citas = citas;
       this.alumnos = alumnos;
    }
   
    public int getIdSede() {
        return this.idSede;
    }
    
    public void setIdSede(int idSede) {
        this.idSede = idSede;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }




}


