
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ActividadPropuesta
{

    public ActividadPropuesta()
    {

        this.Observacion = new HashSet<Observacion>();

        this.SubActividad = new HashSet<SubActividad>();

    }


    public int idactividadPropuesta { get; set; }

    public string nombre { get; set; }

    public Nullable<System.DateTime> fechaInicio { get; set; }

    public Nullable<System.DateTime> fechaTermino { get; set; }

    public string descripcion { get; set; }

    public Nullable<int> idPlan { get; set; }



    public virtual PlanGobierno PlanGobierno { get; set; }

    public virtual ICollection<Observacion> Observacion { get; set; }

    public virtual ICollection<SubActividad> SubActividad { get; set; }

}

}
