
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ActividadPlanAsignatura
{

    public int idActividadPlanAsignatura { get; set; }

    public string actividad { get; set; }

    public System.DateTime fechaInicio { get; set; }

    public System.DateTime fechaFin { get; set; }

    public int porcentajeAvance { get; set; }

    public int idPlanAsignatura { get; set; }

    public int idPersona { get; set; }

    public System.DateTime fechaCreacion { get; set; }

    public Nullable<System.DateTime> fechaModificacion { get; set; }

    public int idEmpleado { get; set; }



    public virtual Empleado Empleado { get; set; }

    public virtual PlanAsignatura PlanAsignatura { get; set; }

}

}
