
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Agenda
{

    public Agenda()
    {

        this.AprobacionAgenda = new HashSet<AprobacionAgenda>();

        this.Calendario = new HashSet<Calendario>();

        this.Feriado = new HashSet<Feriado>();

    }


    public string idAgenda { get; set; }

    public string descripcion { get; set; }

    public System.DateTime fechaApertura { get; set; }

    public System.DateTime fechaCierre { get; set; }

    public System.DateTime fechaInicioEscolar { get; set; }

    public System.DateTime FechaTerminoEscolar { get; set; }

    public int estado { get; set; }

    public string usuCreacion { get; set; }

    public System.DateTime fecCreacion { get; set; }

    public string usuModificacion { get; set; }

    public Nullable<System.DateTime> fecModificacion { get; set; }



    public virtual ICollection<AprobacionAgenda> AprobacionAgenda { get; set; }

    public virtual ICollection<Calendario> Calendario { get; set; }

    public virtual ICollection<Feriado> Feriado { get; set; }

}

}
