
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Alumno
{

    public Alumno()
    {

        this.AlumnoEmpadronado = new HashSet<AlumnoEmpadronado>();

        this.Integrante = new HashSet<Integrante>();

        this.ExpedienteAdmision = new HashSet<ExpedienteAdmision>();

        this.Matricula = new HashSet<Matricula>();

    }


    public int idAlumno { get; set; }

    public string estado { get; set; }

    public Nullable<int> idPersona { get; set; }

    public Nullable<int> idApoderado { get; set; }

    public Nullable<int> idSede { get; set; }

    public Nullable<int> idGrado { get; set; }



    public virtual ICollection<AlumnoEmpadronado> AlumnoEmpadronado { get; set; }

    public virtual ICollection<Integrante> Integrante { get; set; }

    public virtual Sede Sede { get; set; }

    public virtual ICollection<ExpedienteAdmision> ExpedienteAdmision { get; set; }

    public virtual ICollection<Matricula> Matricula { get; set; }

    public virtual Persona Persona { get; set; }

    public virtual Apoderado Apoderado { get; set; }

    public virtual Grado Grado { get; set; }

}

}
