
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AreaCurricular
{

    public AreaCurricular()
    {

        this.PlanArea = new HashSet<PlanArea>();

        this.PlanProyectoPedagogico = new HashSet<PlanProyectoPedagogico>();

        this.CurriculaBaseCompetencia = new HashSet<CurriculaBaseCompetencia>();

        this.Curso = new HashSet<Curso>();

        this.PlanEstudiosBase = new HashSet<PlanEstudiosBase>();

    }


    public int IdAreaCurricular { get; set; }

    public string Nombre { get; set; }

    public decimal Horas { get; set; }

    public string Abreviatura { get; set; }



    public virtual ICollection<PlanArea> PlanArea { get; set; }

    public virtual ICollection<PlanProyectoPedagogico> PlanProyectoPedagogico { get; set; }

    public virtual ICollection<CurriculaBaseCompetencia> CurriculaBaseCompetencia { get; set; }

    public virtual ICollection<Curso> Curso { get; set; }

    public virtual ICollection<PlanEstudiosBase> PlanEstudiosBase { get; set; }

}

}
