
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Asesor
{

    public Asesor()
    {

        this.PartidoPostulante = new HashSet<PartidoPostulante>();

    }


    public int idAsesor { get; set; }

    public string nombre { get; set; }

    public Nullable<int> idPersona { get; set; }



    public virtual Persona Persona { get; set; }

    public virtual ICollection<PartidoPostulante> PartidoPostulante { get; set; }

}

}
