
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Calendario
{

    public Calendario()
    {

        this.AprobacionCalendario = new HashSet<AprobacionCalendario>();

    }


    public int idCalendario { get; set; }

    public string idAgenda { get; set; }

    public string tipo { get; set; }

    public int estado { get; set; }

    public string usuCreacion { get; set; }

    public System.DateTime fecCreacion { get; set; }

    public string usuModificacion { get; set; }

    public Nullable<System.DateTime> fecModificacion { get; set; }



    public virtual Agenda Agenda { get; set; }

    public virtual ICollection<AprobacionCalendario> AprobacionCalendario { get; set; }

}

}
