
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Cargo
{

    public Cargo()
    {

        this.Integrante = new HashSet<Integrante>();

    }


    public int idCargo { get; set; }

    public string tipoCargo { get; set; }

    public Nullable<int> anoAcademico { get; set; }



    public virtual ICollection<Integrante> Integrante { get; set; }

}

}
