
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Competencia
{

    public Competencia()
    {

        this.Capacidad = new HashSet<Capacidad>();

        this.CurriculaBaseCompetencia = new HashSet<CurriculaBaseCompetencia>();

    }


    public int IdCompetencia { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }



    public virtual ICollection<Capacidad> Capacidad { get; set; }

    public virtual ICollection<CurriculaBaseCompetencia> CurriculaBaseCompetencia { get; set; }

}

}
