
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Contrato
{

    public int idEmpleado { get; set; }

    public int numeroContrato { get; set; }

    public string tipoContrato { get; set; }

    public Nullable<System.DateTime> fechaInicioContrato { get; set; }

    public Nullable<System.DateTime> fechaFinContrato { get; set; }

    public Nullable<decimal> salario { get; set; }

    public string estadoContrato { get; set; }

    public int idPuesto { get; set; }

    public string usuarioCreacion { get; set; }

    public Nullable<System.DateTime> fechaCreacion { get; set; }

    public string usuarioModificacion { get; set; }

    public Nullable<System.DateTime> fechaModificacion { get; set; }



    public virtual Empleado Empleado { get; set; }

}

}
