
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Contrato
{

    public int idEmpleado { get; set; }

    public int idPuesto { get; set; }

    public Nullable<System.DateTime> fechaInicioContrato { get; set; }

    public Nullable<System.DateTime> fechaFinContrato { get; set; }

    public Nullable<decimal> salario { get; set; }

    public Nullable<int> idTipoContrato { get; set; }

    public int idContrato { get; set; }

    public Nullable<int> idConvocatoria { get; set; }



    public virtual Empleado Empleado { get; set; }

    public virtual Puesto Puesto { get; set; }

    public virtual Convocatoria Convocatoria { get; set; }

    public virtual TipoContrato TipoContrato { get; set; }

}

}
