
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Convocatoria
{

    public Convocatoria()
    {

        this.Contrato = new HashSet<Contrato>();

    }


    public int idConvocatoria { get; set; }

    public Nullable<System.DateTime> fechaInicioPublicacion { get; set; }

    public Nullable<System.DateTime> fechaFinPublicacion { get; set; }

    public Nullable<int> numeroVacantes { get; set; }

    public string tipoConvocatoria { get; set; }

    public Nullable<int> anoExperiencia { get; set; }

    public string conocimiento { get; set; }

    public Nullable<int> idPuesto { get; set; }

    public Nullable<System.DateTime> fechaVencimientoDocumento { get; set; }

    public Nullable<int> idTipoPuesto { get; set; }

    public Nullable<int> idArea { get; set; }

    public Nullable<int> idDesarrollo { get; set; }



    public virtual Area Area { get; set; }

    public virtual ICollection<Contrato> Contrato { get; set; }

    public virtual Puesto Puesto { get; set; }

    public virtual Desarrollo Desarrollo { get; set; }

    public virtual TipoPuesto TipoPuesto { get; set; }

}

}
