
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Curricula
{

    public Curricula()
    {

        this.DetalleCurricula = new HashSet<DetalleCurricula>();

    }


    public int IdCurricula { get; set; }

    public Nullable<int> IdCurriculaBase { get; set; }

    public string Codigo { get; set; }

    public Nullable<int> Año { get; set; }

    public string Descripcion { get; set; }

    public Nullable<int> Estado { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public Nullable<System.DateTime> FechaAprobacion { get; set; }

    public Nullable<System.DateTime> FechaRechazo { get; set; }

    public Nullable<int> IdUsuarioCreacion { get; set; }

    public string NoUsuarioCreacion { get; set; }

    public Nullable<int> IdUsuarioAprobacion { get; set; }

    public Nullable<int> IdUsuarioRechazo { get; set; }

    public string MotivoRechazo { get; set; }



    public virtual CurriculaBase CurriculaBase { get; set; }

    public virtual ICollection<DetalleCurricula> DetalleCurricula { get; set; }

}

}
