
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CurriculaBaseCompetencia
{

    public int IdCurriculaBaseCompetencia { get; set; }

    public int IdCurriculaBase { get; set; }

    public int IdCompetencia { get; set; }

    public int IdAreaCurricular { get; set; }



    public virtual AreaCurricular AreaCurricular { get; set; }

    public virtual Competencia Competencia { get; set; }

    public virtual CurriculaBase CurriculaBase { get; set; }

}

}
