
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Curso
{

    public Curso()
    {

        this.CursoTema = new HashSet<CursoTema>();

        this.PlanEstudiosBase = new HashSet<PlanEstudiosBase>();

        this.Docente = new HashSet<Docente>();

    }


    public int IdCurso { get; set; }

    public string Codigo { get; set; }

    public string Nombre { get; set; }

    public string Sumilla { get; set; }

    public bool Estado { get; set; }

    public int IdGrado { get; set; }

    public int IdAreaCurricular { get; set; }

    public int IdEmpleado { get; set; }



    public virtual AreaCurricular AreaCurricular { get; set; }

    public virtual Empleado Empleado { get; set; }

    public virtual Grado Grado { get; set; }

    public virtual ICollection<CursoTema> CursoTema { get; set; }

    public virtual ICollection<PlanEstudiosBase> PlanEstudiosBase { get; set; }

    public virtual ICollection<Docente> Docente { get; set; }

}

}
