
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CursoTema
{

    public int IdCurso { get; set; }

    public int IdUnidad { get; set; }

    public string Temario { get; set; }



    public virtual Curso Curso { get; set; }

    public virtual Unidad Unidad { get; set; }

}

}
