
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Curso
{

    public Curso()
    {

        this.PlanAsignatura = new HashSet<PlanAsignatura>();

        this.CursoTema = new HashSet<CursoTema>();

        this.DetalleCurricula = new HashSet<DetalleCurricula>();

        this.Empleado1 = new HashSet<Empleado>();

    }


    public int IdCurso { get; set; }

    public string Codigo { get; set; }

    public string Nombre { get; set; }

    public string Sumilla { get; set; }

    public bool Estado { get; set; }

    public int IdGrado { get; set; }

    public int IdAreaCurricular { get; set; }

    public int IdEmpleado { get; set; }



    public virtual ICollection<PlanAsignatura> PlanAsignatura { get; set; }

    public virtual AreaCurricular AreaCurricular { get; set; }

    public virtual Empleado Empleado { get; set; }

    public virtual Grado Grado { get; set; }

    public virtual ICollection<CursoTema> CursoTema { get; set; }

    public virtual ICollection<DetalleCurricula> DetalleCurricula { get; set; }

    public virtual ICollection<Empleado> Empleado1 { get; set; }

}

}
