

//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class InnovaEntities : DbContext
{
    public InnovaEntities()
        : base("name=InnovaEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<sysdiagrams> sysdiagrams { get; set; }

    public DbSet<Alumno> Alumno { get; set; }

    public DbSet<Apoderado> Apoderado { get; set; }

    public DbSet<Area> Area { get; set; }

    public DbSet<Cronograma> Cronograma { get; set; }

    public DbSet<DocumentoIdentidad> DocumentoIdentidad { get; set; }

    public DbSet<ExpedienteAdmision> ExpedienteAdmision { get; set; }

    public DbSet<Matricula> Matricula { get; set; }

    public DbSet<Parentesco> Parentesco { get; set; }

    public DbSet<Proceso> Proceso { get; set; }

    public DbSet<Seccion> Seccion { get; set; }

    public DbSet<Sede> Sede { get; set; }

    public DbSet<Agenda> Agenda { get; set; }

    public DbSet<Ambiente> Ambiente { get; set; }

    public DbSet<AprobacionAgenda> AprobacionAgenda { get; set; }

    public DbSet<AprobacionCalendario> AprobacionCalendario { get; set; }

    public DbSet<AprobacionSolicitudActividad> AprobacionSolicitudActividad { get; set; }

    public DbSet<Calendario> Calendario { get; set; }

    public DbSet<Feriado> Feriado { get; set; }

    public DbSet<SolicitudActividad> SolicitudActividad { get; set; }

    public DbSet<ActividadPlanAsignatura> ActividadPlanAsignatura { get; set; }

    public DbSet<ActividadPlanProyectoPedagogico> ActividadPlanProyectoPedagogico { get; set; }

    public DbSet<Meta> Meta { get; set; }

    public DbSet<PeriodoAcademico> PeriodoAcademico { get; set; }

    public DbSet<PlanArea> PlanArea { get; set; }

    public DbSet<PlanAsignatura> PlanAsignatura { get; set; }

    public DbSet<PlanEstudio> PlanEstudio { get; set; }

    public DbSet<PlanProyectoPedagogico> PlanProyectoPedagogico { get; set; }

    public DbSet<ActividadAcademicaPlan> ActividadAcademicaPlan { get; set; }

    public DbSet<ActividadPropuesta> ActividadPropuesta { get; set; }

    public DbSet<AlumnoEmpadronado> AlumnoEmpadronado { get; set; }

    public DbSet<Asesor> Asesor { get; set; }

    public DbSet<Cargo> Cargo { get; set; }

    public DbSet<DetalleProceso> DetalleProceso { get; set; }

    public DbSet<Instrumento> Instrumento { get; set; }

    public DbSet<Integrante> Integrante { get; set; }

    public DbSet<Observacion> Observacion { get; set; }

    public DbSet<ParametroTiempo> ParametroTiempo { get; set; }

    public DbSet<PartidoPostulante> PartidoPostulante { get; set; }

    public DbSet<PlanGobierno> PlanGobierno { get; set; }

    public DbSet<Roles> Roles { get; set; }

    public DbSet<SubActividad> SubActividad { get; set; }

    public DbSet<Voto> Voto { get; set; }

    public DbSet<AreaCurricular> AreaCurricular { get; set; }

    public DbSet<Capacidad> Capacidad { get; set; }

    public DbSet<Competencia> Competencia { get; set; }

    public DbSet<Curricula> Curricula { get; set; }

    public DbSet<CurriculaBase> CurriculaBase { get; set; }

    public DbSet<CurriculaBaseCompetencia> CurriculaBaseCompetencia { get; set; }

    public DbSet<Curso> Curso { get; set; }

    public DbSet<CursoTema> CursoTema { get; set; }

    public DbSet<DetalleCurricula> DetalleCurricula { get; set; }

    public DbSet<DetalleCurriculaCalificacion> DetalleCurriculaCalificacion { get; set; }

    public DbSet<DetalleCurriculaProfesor> DetalleCurriculaProfesor { get; set; }

    public DbSet<DetalleCurriculaTema> DetalleCurriculaTema { get; set; }

    public DbSet<Grado> Grado { get; set; }

    public DbSet<Nivel> Nivel { get; set; }

    public DbSet<Parametro> Parametro { get; set; }

    public DbSet<PlanEstudiosBase> PlanEstudiosBase { get; set; }

    public DbSet<TipoCalificación> TipoCalificación { get; set; }

    public DbSet<Unidad> Unidad { get; set; }

    public DbSet<Banco> Banco { get; set; }

    public DbSet<Candidato> Candidato { get; set; }

    public DbSet<Contrato> Contrato { get; set; }

    public DbSet<Convocatoria> Convocatoria { get; set; }

    public DbSet<ConvocatoriaCandidato> ConvocatoriaCandidato { get; set; }

    public DbSet<Desarrollo> Desarrollo { get; set; }

    public DbSet<Empleado> Empleado { get; set; }

    public DbSet<EstadoCandidato> EstadoCandidato { get; set; }

    public DbSet<EstadoCivil> EstadoCivil { get; set; }

    public DbSet<EstadoEmpleado> EstadoEmpleado { get; set; }

    public DbSet<FondoPensiones> FondoPensiones { get; set; }

    public DbSet<Nacionalidad> Nacionalidad { get; set; }

    public DbSet<NivelEstudio> NivelEstudio { get; set; }

    public DbSet<Persona> Persona { get; set; }

    public DbSet<Puesto> Puesto { get; set; }

    public DbSet<Seguro> Seguro { get; set; }

    public DbSet<TipoContrato> TipoContrato { get; set; }

    public DbSet<TipoPuesto> TipoPuesto { get; set; }

    public DbSet<Usuario> Usuario { get; set; }

}

}

