
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Desarrollo
{

    public Desarrollo()
    {

        this.Convocatoria = new HashSet<Convocatoria>();

    }


    public int idDesarrollo { get; set; }

    public string descripcionDesarrollo { get; set; }



    public virtual ICollection<Convocatoria> Convocatoria { get; set; }

}

}
