
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleProceso
{

    public DetalleProceso()
    {

        this.AlumnoEmpadronado = new HashSet<AlumnoEmpadronado>();

        this.PlanGobierno = new HashSet<PlanGobierno>();

        this.Voto = new HashSet<Voto>();

    }


    public int idProceso { get; set; }

    public string nombreProceso { get; set; }

    public Nullable<System.DateTime> FechaInicio { get; set; }

    public Nullable<System.DateTime> FechaFin { get; set; }

    public Nullable<int> idPersona { get; set; }



    public virtual ICollection<AlumnoEmpadronado> AlumnoEmpadronado { get; set; }

    public virtual Persona Persona { get; set; }

    public virtual ICollection<PlanGobierno> PlanGobierno { get; set; }

    public virtual ICollection<Voto> Voto { get; set; }

}

}
