
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleCurriculaCalificacion
{

    public int IdDetalleCurriculaCalificacion { get; set; }

    public Nullable<int> IdDetalleCurricula { get; set; }

    public Nullable<int> IdTipoCalificacion { get; set; }

    public Nullable<decimal> ValorCalificacion { get; set; }



    public virtual DetalleCurricula DetalleCurricula { get; set; }

    public virtual TipoCalificación TipoCalificación { get; set; }

}

}
