
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleCurricula
{

    public DetalleCurricula()
    {

        this.DetalleCurriculaCalificacion = new HashSet<DetalleCurriculaCalificacion>();

        this.DetalleCurriculaProfesor = new HashSet<DetalleCurriculaProfesor>();

        this.DetalleCurriculaTema = new HashSet<DetalleCurriculaTema>();

    }


    public int IdCurricula { get; set; }

    public int IdDetalleCurricula { get; set; }

    public Nullable<int> IdCurso { get; set; }

    public Nullable<int> IdCoordinador { get; set; }

    public string Item { get; set; }

    public Nullable<decimal> HrsAsignadas { get; set; }



    public virtual Curricula Curricula { get; set; }

    public virtual Curso Curso { get; set; }

    public virtual Empleado Empleado { get; set; }

    public virtual ICollection<DetalleCurriculaCalificacion> DetalleCurriculaCalificacion { get; set; }

    public virtual ICollection<DetalleCurriculaProfesor> DetalleCurriculaProfesor { get; set; }

    public virtual ICollection<DetalleCurriculaTema> DetalleCurriculaTema { get; set; }

}

}
