
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Empleado
{

    public Empleado()
    {

        this.ActividadPlanAsignatura = new HashSet<ActividadPlanAsignatura>();

        this.ActividadPlanProyectoPedagogico = new HashSet<ActividadPlanProyectoPedagogico>();

        this.PlanAsignatura = new HashSet<PlanAsignatura>();

        this.Curso = new HashSet<Curso>();

        this.DetalleCurricula = new HashSet<DetalleCurricula>();

        this.DetalleCurriculaProfesor = new HashSet<DetalleCurriculaProfesor>();

        this.Contrato = new HashSet<Contrato>();

        this.Curso1 = new HashSet<Curso>();

    }


    public int idEmpleado { get; set; }

    public int idPersona { get; set; }

    public Nullable<int> idBanco { get; set; }

    public string telefonoEmergencia { get; set; }

    public string contactoEmergencia { get; set; }

    public Nullable<int> idCandidato { get; set; }

    public Nullable<int> idFondoPensiones { get; set; }

    public Nullable<int> idSeguro { get; set; }

    public Nullable<int> idEstadoEmpleado { get; set; }

    public Nullable<int> idNivelEstudios { get; set; }

    public string cuentaBanco { get; set; }

    public string codigoFotocheck { get; set; }



    public virtual ICollection<ActividadPlanAsignatura> ActividadPlanAsignatura { get; set; }

    public virtual ICollection<ActividadPlanProyectoPedagogico> ActividadPlanProyectoPedagogico { get; set; }

    public virtual ICollection<PlanAsignatura> PlanAsignatura { get; set; }

    public virtual ICollection<Curso> Curso { get; set; }

    public virtual ICollection<DetalleCurricula> DetalleCurricula { get; set; }

    public virtual ICollection<DetalleCurriculaProfesor> DetalleCurriculaProfesor { get; set; }

    public virtual Banco Banco { get; set; }

    public virtual Candidato Candidato { get; set; }

    public virtual ICollection<Contrato> Contrato { get; set; }

    public virtual Persona Persona { get; set; }

    public virtual EstadoEmpleado EstadoEmpleado { get; set; }

    public virtual FondoPensiones FondoPensiones { get; set; }

    public virtual NivelEstudio NivelEstudio { get; set; }

    public virtual Seguro Seguro { get; set; }

    public virtual ICollection<Curso> Curso1 { get; set; }

}

}
