
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Empleado
{

    public Empleado()
    {

        this.Contrato = new HashSet<Contrato>();

        this.Curso = new HashSet<Curso>();

    }


    public int idEmpleado { get; set; }

    public int idPersona { get; set; }

    public string fondoPensiones { get; set; }

    public Nullable<System.DateTime> fechaIngreso { get; set; }

    public string estadoEmpleado { get; set; }

    public string usuarioCreacion { get; set; }

    public Nullable<System.DateTime> fechaCreacion { get; set; }

    public string usuarioModificacion { get; set; }

    public Nullable<System.DateTime> fechaModificacion { get; set; }

    public Nullable<int> cantHijos { get; set; }

    public string estadoCivil { get; set; }

    public Nullable<int> numeroEPS { get; set; }

    public Nullable<int> idBanco { get; set; }

    public Nullable<decimal> numeroCuentaHaberes { get; set; }

    public string telefonoEmergencia { get; set; }

    public string contactoEmergencia { get; set; }

    public string gradoEstudios { get; set; }

    public string indicadorEPS { get; set; }



    public virtual ICollection<Contrato> Contrato { get; set; }

    public virtual ICollection<Curso> Curso { get; set; }

    public virtual Persona Persona { get; set; }

}

}
