
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ExpedienteAdmision
{

    public int idExpedienteAdmision { get; set; }

    public Nullable<System.DateTime> fechaRegistro { get; set; }

    public string estado { get; set; }

    public Nullable<int> idAlumno { get; set; }

    public string resultInfocorp { get; set; }

    public string obsPsicologicas { get; set; }

    public string resultEvaPsico { get; set; }

    public Nullable<int> resultBloqueLetras { get; set; }

    public Nullable<int> resultBloqueMatCiencias { get; set; }

    public Nullable<int> resultRM_RV { get; set; }

    public string codigoExpediente { get; set; }



    public virtual Alumno Alumno { get; set; }

}

}
