
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Grado
{

    public Grado()
    {

        this.Seccion = new HashSet<Seccion>();

        this.PlanArea = new HashSet<PlanArea>();

        this.PlanProyectoPedagogico = new HashSet<PlanProyectoPedagogico>();

        this.Curso = new HashSet<Curso>();

        this.PlanEstudiosBase = new HashSet<PlanEstudiosBase>();

        this.Alumno = new HashSet<Alumno>();

    }


    public int IdGrado { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public int IdNivel { get; set; }



    public virtual ICollection<Seccion> Seccion { get; set; }

    public virtual ICollection<PlanArea> PlanArea { get; set; }

    public virtual ICollection<PlanProyectoPedagogico> PlanProyectoPedagogico { get; set; }

    public virtual ICollection<Curso> Curso { get; set; }

    public virtual Nivel Nivel { get; set; }

    public virtual ICollection<PlanEstudiosBase> PlanEstudiosBase { get; set; }

    public virtual ICollection<Alumno> Alumno { get; set; }

}

}
