
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Instrumento
{

    public Instrumento()
    {

        this.Observacion = new HashSet<Observacion>();

    }


    public int idInstrumento { get; set; }

    public string Descripcion { get; set; }

    public string Objetivo { get; set; }

    public Nullable<int> idPlan { get; set; }

    public string nombre { get; set; }



    public virtual PlanGobierno PlanGobierno { get; set; }

    public virtual ICollection<Observacion> Observacion { get; set; }

}

}
