
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Integrante
{

    public int idIntegrante { get; set; }

    public Nullable<int> idAlumno { get; set; }

    public Nullable<int> idCargo { get; set; }

    public Nullable<int> idPartido { get; set; }



    public virtual Alumno Alumno { get; set; }

    public virtual Cargo Cargo { get; set; }

    public virtual PartidoPostulante PartidoPostulante { get; set; }

}

}
