
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Matricula
{

    public int idMatricula { get; set; }

    public Nullable<System.DateTime> fechaMatricula { get; set; }

    public Nullable<int> idProceso { get; set; }

    public Nullable<int> idAlumno { get; set; }

    public Nullable<int> idSeccion { get; set; }



    public virtual Alumno Alumno { get; set; }

    public virtual Proceso Proceso { get; set; }

    public virtual Seccion Seccion { get; set; }

}

}
