
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Observacion
{

    public int idObservacion { get; set; }

    public string Descripcion { get; set; }

    public string NivelObservacion { get; set; }

    public Nullable<int> idInstrumento { get; set; }

    public Nullable<int> idActividadPropuesta { get; set; }

    public Nullable<int> idactPlan { get; set; }



    public virtual ActividadAcademicaPlan ActividadAcademicaPlan { get; set; }

    public virtual ActividadPropuesta ActividadPropuesta { get; set; }

    public virtual Instrumento Instrumento { get; set; }

}

}
