
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Parentesco
{

    public Parentesco()
    {

        this.Apoderado = new HashSet<Apoderado>();

    }


    public int idParentesco { get; set; }

    public string descripcion { get; set; }



    public virtual ICollection<Apoderado> Apoderado { get; set; }

}

}
