
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PartidoPostulante
{

    public PartidoPostulante()
    {

        this.Integrante = new HashSet<Integrante>();

        this.PlanGobierno = new HashSet<PlanGobierno>();

        this.Voto = new HashSet<Voto>();

    }


    public int idPartido { get; set; }

    public string Nombre { get; set; }

    public byte[] Logo { get; set; }

    public Nullable<int> idAsesor { get; set; }

    public string FechaReg { get; set; }

    public string Estado { get; set; }



    public virtual Asesor Asesor { get; set; }

    public virtual ICollection<Integrante> Integrante { get; set; }

    public virtual ICollection<PlanGobierno> PlanGobierno { get; set; }

    public virtual ICollection<Voto> Voto { get; set; }

}

}
