
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PeriodoAcademico
{

    public PeriodoAcademico()
    {

        this.PlanProyectoPedagogico = new HashSet<PlanProyectoPedagogico>();

        this.PlanArea = new HashSet<PlanArea>();

    }


    public int idPeriodoAcademico { get; set; }

    public string periodo { get; set; }

    public System.DateTime fechaInicio { get; set; }

    public System.DateTime fechaFin { get; set; }



    public virtual ICollection<PlanProyectoPedagogico> PlanProyectoPedagogico { get; set; }

    public virtual ICollection<PlanArea> PlanArea { get; set; }

}

}
