
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Persona
{

    public Persona()
    {

        this.Empleado = new HashSet<Empleado>();

    }


    public int idPersona { get; set; }

    public string nombre { get; set; }

    public string apellidoPaterno { get; set; }

    public string apellidoMaterno { get; set; }

    public string direccion { get; set; }

    public string telefono { get; set; }

    public string correoElectronico { get; set; }

    public Nullable<int> tipoDocumentoIdentidad { get; set; }

    public string documentoIdentidad { get; set; }

    public string nacionalidad { get; set; }

    public string genero { get; set; }

    public Nullable<System.DateTime> fechaNacimiento { get; set; }

    public string celular { get; set; }

    public string usuarioCreacion { get; set; }

    public Nullable<System.DateTime> fechaCreacion { get; set; }

    public string usuarioModificacion { get; set; }

    public Nullable<System.DateTime> fechaModificacion { get; set; }



    public virtual DocumentoIdentidad DocumentoIdentidad1 { get; set; }

    public virtual ICollection<Empleado> Empleado { get; set; }

}

}
