
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Persona
{

    public Persona()
    {

        this.Alumno = new HashSet<Alumno>();

        this.Apoderado = new HashSet<Apoderado>();

        this.Asesor = new HashSet<Asesor>();

        this.DetalleProceso = new HashSet<DetalleProceso>();

        this.Candidato = new HashSet<Candidato>();

        this.Empleado = new HashSet<Empleado>();

        this.Usuario = new HashSet<Usuario>();

    }


    public int idPersona { get; set; }

    public string nombre { get; set; }

    public string apellidoPaterno { get; set; }

    public string apellidoMaterno { get; set; }

    public string direccion { get; set; }

    public string telefono { get; set; }

    public string correoElectronico { get; set; }

    public Nullable<int> tipoDocumentoIdentidad { get; set; }

    public string documentoIdentidad { get; set; }

    public string genero { get; set; }

    public Nullable<System.DateTime> fechaNacimiento { get; set; }

    public string celular { get; set; }

    public Nullable<int> nroHijos { get; set; }

    public Nullable<int> idEstadoCivil { get; set; }



    public virtual ICollection<Alumno> Alumno { get; set; }

    public virtual ICollection<Apoderado> Apoderado { get; set; }

    public virtual DocumentoIdentidad DocumentoIdentidad1 { get; set; }

    public virtual ICollection<Asesor> Asesor { get; set; }

    public virtual ICollection<DetalleProceso> DetalleProceso { get; set; }

    public virtual ICollection<Candidato> Candidato { get; set; }

    public virtual ICollection<Empleado> Empleado { get; set; }

    public virtual EstadoCivil EstadoCivil { get; set; }

    public virtual ICollection<Usuario> Usuario { get; set; }

}

}
