
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PlanArea
{

    public PlanArea()
    {

        this.PlanAsignatura = new HashSet<PlanAsignatura>();

    }


    public int idPlanArea { get; set; }

    public string nombre { get; set; }

    public string objetivos { get; set; }

    public string criterios { get; set; }

    public string requisitos { get; set; }

    public string estado { get; set; }

    public string documento { get; set; }

    public int idPeriodoAcademico { get; set; }

    public int idPlanEstudio { get; set; }

    public int idGrado { get; set; }

    public int idAreaCurricular { get; set; }

    public Nullable<System.DateTime> fechaCreacion { get; set; }

    public Nullable<System.DateTime> fechaModificacion { get; set; }



    public virtual PeriodoAcademico PeriodoAcademico { get; set; }

    public virtual PlanEstudio PlanEstudio { get; set; }

    public virtual Grado Grado { get; set; }

    public virtual AreaCurricular AreaCurricular { get; set; }

    public virtual ICollection<PlanAsignatura> PlanAsignatura { get; set; }

}

}
