
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PlanEstudio
{

    public PlanEstudio()
    {

        this.PlanArea = new HashSet<PlanArea>();

        this.PlanProyectoPedagogico = new HashSet<PlanProyectoPedagogico>();

    }


    public int idPlanEstudio { get; set; }

    public string nombre { get; set; }

    public int anio { get; set; }

    public string objetivos { get; set; }

    public string requisitos { get; set; }

    public string estado { get; set; }

    public string documento { get; set; }



    public virtual ICollection<PlanArea> PlanArea { get; set; }

    public virtual ICollection<PlanProyectoPedagogico> PlanProyectoPedagogico { get; set; }

}

}
