
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PlanGobierno
{

    public PlanGobierno()
    {

        this.ActividadAcademicaPlan = new HashSet<ActividadAcademicaPlan>();

        this.ActividadPropuesta = new HashSet<ActividadPropuesta>();

        this.Instrumento = new HashSet<Instrumento>();

    }


    public int idplan { get; set; }

    public Nullable<System.DateTime> FechaReg { get; set; }

    public string Estado { get; set; }

    public string Objetivo { get; set; }

    public Nullable<System.DateTime> FechaAprob { get; set; }

    public Nullable<int> codAlumno { get; set; }

    public Nullable<int> idProceso { get; set; }

    public Nullable<int> idPartido { get; set; }



    public virtual ICollection<ActividadAcademicaPlan> ActividadAcademicaPlan { get; set; }

    public virtual ICollection<ActividadPropuesta> ActividadPropuesta { get; set; }

    public virtual DetalleProceso DetalleProceso { get; set; }

    public virtual ICollection<Instrumento> Instrumento { get; set; }

    public virtual PartidoPostulante PartidoPostulante { get; set; }

}

}
