
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Proceso
{

    public Proceso()
    {

        this.Matricula = new HashSet<Matricula>();

    }


    public int idProceso { get; set; }

    public string tipo { get; set; }

    public Nullable<System.DateTime> fechaInicio { get; set; }

    public Nullable<System.DateTime> fechaFin { get; set; }

    public Nullable<int> idCronograma { get; set; }



    public virtual Cronograma Cronograma { get; set; }

    public virtual ICollection<Matricula> Matricula { get; set; }

}

}
