
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Sede
{

    public Sede()
    {

        this.Alumno = new HashSet<Alumno>();

    }


    public int idSede { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public string direccion { get; set; }



    public virtual ICollection<Alumno> Alumno { get; set; }

}

}
