
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TipoCalificación
{

    public TipoCalificación()
    {

        this.DetalleCurriculaCalificacion = new HashSet<DetalleCurriculaCalificacion>();

    }


    public int IdTipoCalificación { get; set; }

    public string NomTipoCalificación { get; set; }



    public virtual ICollection<DetalleCurriculaCalificacion> DetalleCurriculaCalificacion { get; set; }

}

}
