
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Usuario
{

    public Usuario()
    {

        this.Roles = new HashSet<Roles>();

    }


    public int IdUsuario { get; set; }

    public string Usuario1 { get; set; }

    public string Email { get; set; }

    public string UPassword { get; set; }

    public int IdPregunta { get; set; }

    public string Respuesta { get; set; }

    public int Estado { get; set; }

    public string UsuCreacion { get; set; }

    public System.DateTime FecCreacion { get; set; }

    public string UsuModificacion { get; set; }

    public Nullable<System.DateTime> FecModificacion { get; set; }

    public Nullable<int> idRol { get; set; }

    public Nullable<int> idPersona { get; set; }

    public Nullable<int> idPerfil { get; set; }



    public virtual ICollection<Roles> Roles { get; set; }

    public virtual Roles Roles1 { get; set; }

    public virtual Persona Persona { get; set; }

}

}
