
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innova.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Voto
{

    public int idVoto { get; set; }

    public Nullable<int> EstadoVoto { get; set; }

    public Nullable<System.DateTime> FechaVoto { get; set; }

    public Nullable<int> idPartido { get; set; }

    public Nullable<int> idProceso { get; set; }



    public virtual DetalleProceso DetalleProceso { get; set; }

    public virtual PartidoPostulante PartidoPostulante { get; set; }

}

}
